#' Example SummarizedExperiment for ProtPipe workflows
#'
#' A packaged `SummarizedExperiment` created from
#' `EXAMPLES/basic_example_data/iPSC.csv`. The object contains protein-level
#' abundance measurements and row metadata from the source file. No external
#' sample metadata are supplied during construction; `colData` contains a
#' single `differentiation_day` column derived from the autogenerated
#' `base_condition` values produced by [create_se()].
#'
#' This dataset is intended for examples, tests, and the getting-started
#' vignette.
#'
#' @format A `SummarizedExperiment` object with one assay named
#'   `intensities`.
#' @source `EXAMPLES/basic_example_data/iPSC.csv`
"protpipe_example_se"
